name: Build and deploy Docker app to Azure

on:
  push:
    branches:
      - master

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# Set up the following secrets in your repository:
#   AZURE_CREDENTIALS, REGISTRY_USERNAME, REGISTRY_PASSWORD, REGISTRY_URL
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: branch-deploys-appservice  # set this to your application's name (by default webappname-appservice)
  CONTAINER_IMAGE_NAME: branch-deploys

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
#
    - name: ACR authentication
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Docker Build & Push to ACR
      run: |
        docker build . -t ${{ secrets.REGISTRY_URL }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_URL }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}

    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: ${{ secrets.REGISTRY_URL }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}
